name: Build and Upload Artifact

on:
  push:
    branches: [ main, master ] # Se activa en push a main o master
  pull_request:
    branches: [ main, master ] # También se activa en pull requests a main o master

jobs:
  build:
    runs-on: windows-latest # Usar el runner más reciente de Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # Combina setup e install en un solo paso
    - name: Setup vcpkg and Install Dependencies
      uses: lukka/run-vcpkg@v11
      id: setupvcpkg # Mantiene el ID si lo necesitas
      with:
        vcpkgGitCommitId: '96d5fb3de135b86d7222c53f2352ca92827a156b'
        # Añade gstreamer y gst-plugins-base a la lista
        vcpkgArguments: openssl pthreads gstreamer gst-plugins-base
        vcpkgTriplet: x64-windows

    - name: Set up Developer Command Prompt for MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      # Usa la variable de entorno VCPKG_ROOT establecida por el paso anterior
      # La sintaxis $env:VARNAME es para PowerShell, que es el shell por defecto en runners Windows
      run: |
        echo "VCPKG_ROOT is $env:VCPKG_ROOT" # Añadido para depuración
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

    - name: Build project
      run: |
        cmake --build build --config Release

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpiplay-windows-build
        path: |
          build/Release/rpiplay.exe
        retention-days: 7